version: "3"
services: 

    redmine-postgresql:
        restart: unless-stopped # always for production
        image: postgres:latest
        environment:
            - POSTGRES_USER=redmine
            - POSTGRES_PASSWORD=password # change PW here
            - POSTGRES_DB=redmine_production
        volumes:
            - ./data/redmine/postgresql:/var/lib/postgresql/data

    redmine:
        restart: unless-stopped # always for production 
        image: sameersbn/redmine:latest
        depends_on:
            - redmine-postgresql
        environment:

            - REDMINE_RELATIVE_URL_ROOT=/redmine
            - DB_ADAPTER=postgresql
            - DB_HOST=redmine-postgresql
            - DB_USER=redmine
            - DB_PASS=password # change PW here
            - DB_NAME=redmine_production

            - SMTP_ENABLED=false
            - SMTP_USER=mailer@example.com
            - SMTP_PASS=password

        volumes:
            - ./data/redmine/redmine:/home/redmine/data
    
    db: # gitea database hostname should be "db"
        restart: unless-stopped # always for production
        image: postgres:latest
        environment:
            - POSTGRES_USER=gitea
            - POSTGRES_PASSWORD=password # change PW here
            - POSTGRES_DB=gitea
        volumes:
            - ./data/gitea/postgresql:/var/lib/postgresql/data

    gitea:
        restart: 'unless-stopped'
        image: 'gitea/gitea:latest'
        depends_on:
            - db 
        ports:
            - '127.0.0.1:10022:22'
        volumes:
            - ./data/gitea/gitea:/data
            - /home/git/.ssh:/data/git/.ssh
        environment:
            - USER_UID=${GIT_UID}
            - USER_GID=${GIT_GID}
            - DB_TYPE=postgres
            - DB_HOST=db
            - DB_NAME=gitea
            - DB_USER=gitea
            - DB_PASSWORD=password
            - ROOT_URL=/gitea/

    nginx:
        restart: unless-stopped
        image: nginx
        volumes:
            - ./nginx/html:/usr/share/nginx/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
