version: "3"
services: 

    redmine-postgresql:
        restart: unless-stopped # always for production
        image: postgres
        environment:
            - POSTGRES_USER=redmine
            - POSTGRES_PASSWORD=password # change PW here
            - POSTGRES_DB=redmine_production
        volumes:
            - /srv/ProjManSrv/redmine/postgresql:/var/lib/postgresql

    redmine:
        restart: unless-stopped # always for production 
        image: redmine
        depends_on:
            - redmine-postgresql
        ports: 
            - 10083:3000
        environment:

            - REDMINE_DB_POSTGRES=redmine-postgresql
            - REDMINE_DB_USERNAME=redmine
            - REDMINE_DB_PASSWORD=password # change PW here
            - REDMINE_DB_DATABASE=redmine_production

        volumes:
            - /srv/ProjManSrv/redmine/redmine:/usr/src/redmine/files

    nginx:
        restart: unless-stopped
        build: nginx
        volumes:
            - ./nginx/html:/usr/share/nginx/html
        # links: 
            # - redmine:redmine
            # - gitlab:gitlab
        ports:
            - "80:80"
